AP\ParserBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: AP\ParserBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        link:
            type: string
            length: '100'
        title:
            type: string
            length: '50'
        properties:
            type: json_array
        createDate:
            type: integer
            column: crecreate_date
        updateDate:
            type: time
            column: update_date
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
    lifecycleCallbacks: {  }
