AP\ParserBundle\Entity\Site:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '20'
        baseUrl:
            type: string
            length: '20'
            column: base_url
    oneToMany:
        categories:
            targetEntity: Category
            mappedBy: site
    lifecycleCallbacks: {  }
