ap_parser_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: APParserBundle:Default:index }
ap_hotline_parser_index:
    pattern: /hotline
    defaults: { _controller: APParserBundle:HotlineParser:index}
