parameters:
#    ap_parser.example.class: AP\ParserBundle\Example

services:
#    ap_parser.example:
#        class: %ap_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
